spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-travel-booking?createDatabaseIfNotExist=true
    username: root
    password: 123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations: file:src/main/resources/static/

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    username: vdt.ktqs
    password: wimzlvksbfgrmtgl
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  #    spring:
  #      datasource:
  #        url: jdbc:h2:mem:testdb
  #        username: sa
  #        password: ""
  #        driver-class-name: org.h2.Driver
  #      jpa:
  #        database-platform: org.hibernate.dialect.H2Dialect
  #      h2:
  #        console:
  #          enabled: true
  #          path: /h2-console
  #


application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3bde6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000
    refreshToken:
      tokenValidityMilliseconds: 259200000

  firebase:
    bucket-name: upload-photo1-5de50.appspot.com
    download-url: https://firebasestorage.googleapis.com/v0/b/upload-photo1-5de50.appspot.com/o/%s?alt=media
    config-json: F:/DEV/JAVA/Spring/FINAL/travel-booking/src/main/resources/static/assets/admin/firebase/upload-photo1-5de50-firebase-adminsdk-v30gs-12a1905888.json

