spring:
  mail:
    host: smtp.gmail.com
    username: vdt.ktqs
    password: obsmvafqntzczxkh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
